### Loading the Annotator Data

In [2]:
df1=pd.read_table("~/desktop/Individualstudy/Diagrams/annotatorranksfinal.txt",delim_whitespace=True)
df1

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     4     6     2       3    1
ACP       1    0     6     2     4       3    5
ACOG      4    6     0     5     2       3    1
AAFP      3    5     4     0     2       1    6
IARC      1    6     2     4     0       3    5
USPSTF    3    5     4     1     2       0    6
ACR       2    4     1     6     3       4    0

### Loading the data(Matrix search ranks)

In [1]:
import pandas as pd
import numpy as np
df=pd.read_table("~/desktop/Individualstudy/Diagrams/searchresult/matrixsearchranks.txt",delim_whitespace=True)
df

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     5     6       4    3
ACOG      1    4     0     5     6       3    2
AAFP      3    5     2     0     6       1    4
IARC      1    5     2     6     0       3    4
USPSTF    1    5     2     4     6       0    3
ACR       2    4     1     3     6       5    0

In [3]:
d=np.array(df)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[[0 4 1 6 5 2 3]
 [2 0 1 5 6 4 3]
 [1 4 0 5 6 3 2]
 [3 5 2 0 6 1 4]
 [1 5 2 6 0 3 4]
 [1 5 2 4 6 0 3]
 [2 4 1 3 6 5 0]]


In [4]:
c=np.array(df1)

### Finding the inter annotator agreement for search result

In [5]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.5714285714285714
ACP 0.21428571428571408
ACOG 0.4642857142857142
AAFP 0.5714285714285714
IARC 0.8928571428571428
USPSTF 0.24999999999999978
ACR 0.6415094339622642


### Loading the data(search result - scores)

In [6]:
df1=pd.read_table("~/desktop/Individualstudy/Diagrams/searchresult/scores/matrix1.txt",delim_whitespace=True)
df1

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     5     6       4    3
ACOG      1    4     0     5     6       3    2
AAFP      3    5     2     0     6       1    4
IARC      1    5     2     6     0       3    4
USPSTF    1    5     2     4     6       0    3
ACR       2    4     1     3     6       5    0

In [7]:
d0=np.array(df1)

### Finding the Interannotator agreement(search result-scores)

In [8]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d0,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.5714285714285714
ACP 0.21428571428571408
ACOG 0.4642857142857142
AAFP 0.5714285714285714
IARC 0.8928571428571428
USPSTF 0.24999999999999978
ACR 0.6415094339622642


### Loading the data(wordembeddingBioasq-cosinesimilarity-ranks)

In [9]:
import pandas as pd
import numpy as np
df2=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingbioasq/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df2

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     3     6     2       1    4
ACP       2    0     3     1     5       4    6
ACOG      3    5     0     6     4       2    1
AAFP      4    1     2     0     5       3    6
IARC      1    5     3     6     0       2    4
USPSTF    1    5     2     6     4       0    3
ACR       3    5     1     6     4       2    0

In [10]:
d1=np.array(df2)

### Finding the Interannotator agreement (WordembeddingBioasq-cosinesimilarity)

In [ ]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d1,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

### Loading the data (WordembeddingBioasq-WMDistance)

In [12]:
import pandas as pd
import numpy as np
df3=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingbioasq/WMDistance/matrix.txt",delim_whitespace=True)
df3

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     1     6     4       2    3
ACP       1    0     2     5     6       3    4
ACOG      2    4     0     6     5       3    1
AAFP      2    4     3     0     6       1    5
IARC      1    5     2     6     0       3    4
USPSTF    1    4     2     5     6       0    3
ACR       2    5     1     6     4       3    0

In [13]:
d2=np.array(df3)

### Finding the Interannotator agreement (WordembeddingBioasq-WMDistance)

In [14]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d2,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.6785714285714285
ACP 0.4642857142857142
ACOG 0.6785714285714285
AAFP 0.6428571428571428
IARC 0.8928571428571428
USPSTF 0.10714285714285687
ACR 0.9433962264150944


### Loading the data (WordEmbeddingconceptualized -cosinesimilarity)

In [15]:
df4=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingconceptualized/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df4

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    3     2     6     5       1    4
ACP       1    0     2     6     4       3    5
ACOG      3    5     0     6     4       2    1
AAFP      2    3     4     0     6       1    5
IARC      1    3     2     6     0       4    5
USPSTF    3    4     2     6     5       0    1
ACR       3    5     1     6     4       2    0

In [16]:
d3=np.array(df4)

### Finding Interannotator agreement (WordEmbeddingconceptualized - Cosinesimilarity)

In [17]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d3,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2)
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.16666666666666652
ACP 0.6666666666666666
ACOG 0.16666666666666652
AAFP 0.33333333333333326
IARC 0.4999999999999999
USPSTF 0.16666666666666652
ACR 0.33333333333333326


### Loading the data (WordEmbeddingconceptualized -WMDistance)

In [18]:
df5=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingconceptualized/WMDistance/matrix.txt",delim_whitespace=True)
df5

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     6     5       4    3
ACOG      2    4     0     6     5       3    1
AAFP      3    4     2     0     6       1    5
IARC      1    3     2     6     0       5    4
USPSTF    2    4     1     5     6       0    3
ACR       2    4     1     6     5       3    0

In [19]:
d4=np.array(df5)

### Finding Interannotator agreement (WordEmbeddingconceptualized - WMDistance)

In [20]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d4,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.5714285714285714
ACP 0.14285714285714268
ACOG 0.6785714285714285
AAFP 0.607142857142857
IARC 0.6785714285714285
USPSTF 0.07142857142857117
ACR 0.9056603773584906


### Loading the data (WordEmbedding no concept- Cosine similarity)

In [21]:
df6=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingnoconcept/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df6

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     2     6     5       1    3
ACP       1    0     3     6     4       2    5
ACOG      3    4     0     6     5       2    1
AAFP      2    1     4     0     6       3    5
IARC      1    2     4     6     0       3    5
USPSTF    3    4     2     6     5       0    1
ACR       3    4     1     6     5       2    0

In [22]:
d5=np.array(df6)

### Finding the Interannotator agreement(WordEmbedding no concept- Cosine similarity)

In [23]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d5,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2)
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.16666666666666652
ACP 0.4999999999999999
ACOG 0.16666666666666652
AAFP 0.16666666666666652
IARC 0.4999999999999999
USPSTF 0.16666666666666652
ACR 0.4999999999999999


### Loading the data(WordEmbedding no concept-WMDistance)

In [24]:
df7=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingnoconcept/WMDistance/matrix.txt",delim_whitespace=True)
df7

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       3    2
ACP       1    0     2     6     5       3    4
ACOG      2    4     0     5     6       3    1
AAFP      3    4     2     0     6       1    5
IARC      1    3     2     6     0       4    5
USPSTF    1    4     2     5     6       0    3
ACR       2    4     1     5     6       3    0

In [25]:
d6=np.array(df7)

### Finding the Interannotator agreement(WordEmbedding no concept-WMDistance)

In [26]:
from sklearn.metrics import cohen_kappa_score
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for x, y in zip(d6,c):
    label1=x
    label2=y
    interanno=cohen_kappa_score(label1, label2,weights='quadratic')
    p.append(interanno)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.6428571428571428
ACP 0.3928571428571427
ACOG 0.5714285714285714
AAFP 0.607142857142857
IARC 0.75
USPSTF 0.10714285714285687
ACR 0.7924528301886793
