### Loading the Annotator Data

In [18]:
import pandas as pd
import numpy as np
df1=pd.read_table("~/desktop/Individualstudy/Diagrams/annotatorranksfinal.txt",delim_whitespace=True)
df1

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     4     6     2       3    1
ACP       1    0     6     2     4       3    5
ACOG      4    6     0     5     2       3    1
AAFP      3    5     4     0     2       1    6
IARC      1    6     2     4     0       3    5
USPSTF    3    5     4     1     2       0    6
ACR       2    4     1     6     3       4    0

### Loading the data(Matrix search ranks)

In [19]:
df=pd.read_table("~/desktop/Individualstudy/Diagrams/searchresult/matrixsearchranks.txt",delim_whitespace=True)
df

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     5     6       4    3
ACOG      1    4     0     5     6       3    2
AAFP      3    5     2     0     6       1    4
IARC      1    5     2     6     0       3    4
USPSTF    1    5     2     4     6       0    3
ACR       2    4     1     3     6       5    0

In [20]:
d=np.array(df)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[[0 4 1 6 5 2 3]
 [2 0 1 5 6 4 3]
 [1 4 0 5 6 3 2]
 [3 5 2 0 6 1 4]
 [1 5 2 6 0 3 4]
 [1 5 2 4 6 0 3]
 [2 4 1 3 6 5 0]]


In [21]:
c=np.array(df1)

### Finding the wasserstein distance for search result

In [59]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.4285714285714286
ACP 2.0
ACOG 1.4285714285714286
AAFP 1.1428571428571428
IARC 0.5714285714285714
USPSTF 2.0
ACR 1.0


### Loading the data(search result - scores)

In [26]:
df1=pd.read_table("~/desktop/Individualstudy/Diagrams/searchresult/scores/matrix1.txt",delim_whitespace=True)
df1

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     5     6       4    3
ACOG      1    4     0     5     6       3    2
AAFP      3    5     2     0     6       1    4
IARC      1    5     2     6     0       3    4
USPSTF    1    5     2     4     6       0    3
ACR       2    4     1     3     6       5    0

In [27]:
d0=np.array(df1)

### Finding the wasserstein distance(search result-scores)

In [58]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d0,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.4285714285714286
ACP 2.0
ACOG 1.4285714285714286
AAFP 1.1428571428571428
IARC 0.5714285714285714
USPSTF 2.0
ACR 1.0


### Loading the data(wordembeddingBioasq-cosinesimilarity-ranks)

In [31]:
df2=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingbioasq/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df2

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     3     6     2       1    4
ACP       2    0     3     1     5       4    6
ACOG      3    5     0     6     4       2    1
AAFP      4    1     2     0     5       3    6
IARC      1    5     3     6     0       2    4
USPSTF    1    5     2     6     4       0    3
ACR       3    5     1     6     4       2    0

In [32]:
d1=np.array(df2)

### Finding the wasserstein distance (WordembeddingBioasq-cosinesimilarity)

In [57]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d1,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 0.8571428571428571
ACP 1.1428571428571428
ACOG 0.8571428571428571
AAFP 1.7142857142857142
IARC 0.8571428571428571
USPSTF 2.0
ACR 0.7142857142857143


### Loading the data (WordembeddingBioasq-WMDistance)

In [35]:
df3=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingbioasq/WMDistance/matrix.txt",delim_whitespace=True)
df3

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    5     1     6     4       2    3
ACP       1    0     2     5     6       3    4
ACOG      2    4     0     6     5       3    1
AAFP      2    4     3     0     6       1    5
IARC      1    5     2     6     0       3    4
USPSTF    1    4     2     5     6       0    3
ACR       2    5     1     6     4       3    0

In [36]:
d2=np.array(df3)

### Finding the wasserstein distance (WordembeddingBioasq-WMDistance)

In [56]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d2,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.1428571428571428
ACP 1.4285714285714286
ACOG 1.1428571428571428
AAFP 1.1428571428571428
IARC 0.5714285714285714
USPSTF 2.2857142857142856
ACR 0.42857142857142855


### Loading the data (WordEmbeddingconceptualized -cosinesimilarity)

In [39]:
df4=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingconceptualized/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df4

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    3     2     6     5       1    4
ACP       1    0     2     6     4       3    5
ACOG      3    5     0     6     4       2    1
AAFP      2    3     4     0     6       1    5
IARC      1    3     2     6     0       4    5
USPSTF    3    4     2     6     5       0    1
ACR       3    5     1     6     4       2    0

In [40]:
d3=np.array(df4)

### Finding wasserstein distance (WordEmbeddingconceptualized - Cosinesimilarity)

In [55]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d3,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.7142857142857142
ACP 1.1428571428571428
ACOG 0.8571428571428571
AAFP 1.1428571428571428
IARC 0.8571428571428571
USPSTF 2.2857142857142856
ACR 0.7142857142857143


### Loading the data (WordEmbeddingconceptualized -WMDistance)

In [43]:
df5=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingconceptualized/WMDistance/matrix.txt",delim_whitespace=True)
df5

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       2    3
ACP       2    0     1     6     5       4    3
ACOG      2    4     0     6     5       3    1
AAFP      3    4     2     0     6       1    5
IARC      1    3     2     6     0       5    4
USPSTF    2    4     1     5     6       0    3
ACR       2    4     1     6     5       3    0

In [44]:
d4=np.array(df5)

### Finding wasserstein distance (WordEmbeddingconceptualized - WMDistance)

In [54]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d4,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.4285714285714286
ACP 2.0
ACOG 1.1428571428571428
AAFP 1.1428571428571428
IARC 1.1428571428571428
USPSTF 2.2857142857142856
ACR 0.42857142857142855


### Loading the data (WordEmbedding no concept- Cosine similarity)

In [46]:
df6=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingnoconcept/Cosinesimilarity/matrix.txt",delim_whitespace=True)
df6

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     2     6     5       1    3
ACP       1    0     3     6     4       2    5
ACOG      3    4     0     6     5       2    1
AAFP      2    1     4     0     6       3    5
IARC      1    2     4     6     0       3    5
USPSTF    3    4     2     6     5       0    1
ACR       3    4     1     6     5       2    0

In [47]:
d5=np.array(df6)

### Finding the wasserstein distance(WordEmbedding no concept- Cosine similarity)

In [53]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d5,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.4285714285714286
ACP 1.1428571428571428
ACOG 1.1428571428571428
AAFP 1.7142857142857142
IARC 1.1428571428571428
USPSTF 2.2857142857142856
ACR 0.7142857142857143


### Loading the data(WordEmbedding no concept-WMDistance)

In [49]:
df7=pd.read_table("~/desktop/Individualstudy/Diagrams/wordembeddingnoconcept/WMDistance/matrix.txt",delim_whitespace=True)
df7

/Users/seetha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


ACS  ACP  ACOG  AAFP  IARC  USPSTF  ACR
ACS       0    4     1     6     5       3    2
ACP       1    0     2     6     5       3    4
ACOG      2    4     0     5     6       3    1
AAFP      3    4     2     0     6       1    5
IARC      1    3     2     6     0       4    5
USPSTF    1    4     2     5     6       0    3
ACR       2    4     1     5     6       3    0

In [50]:
d6=np.array(df7)

### Finding the wasserstein distance(WordEmbedding no concept-WMDistance)

In [52]:
from scipy.stats import wasserstein_distance
q=["ACS","ACP","ACOG","AAFP","IARC","USPSTF","ACR"]
p=[]
for i,g in zip(d6,c):
    dist1=0
    for j,t in zip(i,g):
        dist=wasserstein_distance([j],[t])
        dist1 = dist1 +dist
    distance=dist1/7
    p.append(distance)

for i in range(len(p)):
    print(q[i],p[i])

ACS 1.1428571428571428
ACP 1.4285714285714286
ACOG 1.1428571428571428
AAFP 1.1428571428571428
IARC 0.8571428571428571
USPSTF 2.2857142857142856
ACR 0.7142857142857143
